# Disables the CRT shader
# This is a workaround  to the shader  blocking most od the screen with black on pixels and some oyher devices. 
# If your device is not effected you can delete this patch file
# Will wash out the colours when active
[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "crt = 70,"
position = "at"
payload = '''
crt = 0,
'''
match_indent = true
times = 1

[[patches]]
[patches.regex]
target = "game.lua"
pattern = ".*G\\.SHADERS\\['CRT'].*\n"
position = "at"
payload = ''''''
match_indent = true
times = 100
